### PR TITLE
Adding NavigationEntry wrapper method for getting history page title.

### PR DESCRIPTION
**Pull request by bsclifton**
cc: @bridiver 

Getting familiar with electron :smile: Adding a method to help w/ getting information used in history.

Would be great if you can help me understand how to test locally (I tried a few things, no luck- I'm ready to update docs after I figure it out)

### CODE REVIEW

**Comment by bsclifton** [comment]
Tested this out locally after making this change https://github.com/bsclifton/browser-laptop/commit/db4352afd593250faccdcf63934046fea9855d4b

Works great :smile: ready for review (and merge if approved)!
cc: @bridiver @bbondy

**Comment by bridiver** [comment]
Looks good! I'll merge after the Chrome 52 update

**Comment by bsclifton** [comment]
Just added (and tested) a new task for installing locally

**Comment by bbondy** [comment]
++ @bridiver pls just cherry-pick into chromium52 once that is sorted out, I have another api that I'm adding that Marshall needs so I'm going to push and merge this and spin v51 based builds for testing.

**Pull request merged**
