### PR TITLE
check_call arguments should be string

### PR DESCRIPTION
**Pull request by ritesh-pandey**

### CODE REVIEW

**Comment by bbondy** [comment]
Can this be upstreamed to atom/electron instead? Then we can get it on our next version bump.

**Comment by ritesh-pandey** [comment]
@bbondy In atom/electron, the source code is different. There is no `retry` parameter.
https://github.com/atom/electron/blob/master/script/install-sysroot.py#L155

How did it get in here?

**Comment by bbondy** [comment]
oh my bad, thanks, I'll merge.  I probably added it a long time ago and forgot :)

**Comment by bbondy** [comment]
Thanks for the fix!

**Pull request merged**
