### PR TITLE
Electron browser

### PR DESCRIPTION
**Pull request by bridiver**

### CODE REVIEW

**Comment by bridiver** [comment]
also requires https://github.com/brave/browser-laptop/pull/2432

**Comment by bridiver** [comment]
I think there may be an issue with this PR. Do not merge yet

**Comment by bridiver** [comment]
ready to go now @bbondy

**Comment by zeke** [comment]
Hi @bridiver. What does this PR do?

**Comment by bridiver** [comment]
the main purpose was to fix some issues with web notifications noted in the second commit, but doing that required disentangling the notifications from the web contents (in upstream there can only be one webcontents per renderer process, but that is not the case for us). Also the start of some general refactoring to separate our browser-specific functionality from the upstream code.

**Comment by bridiver** [comment]
slowly working on some better separation so we can layer functionality on top of electron

**Comment by bbondy** [comment]
++ this is so much better, thanks!

**Pull request merged**
