### PR TITLE
enable sandbox for renderers that don't run node

### PR DESCRIPTION
**Pull request by bridiver**
@bbondy

### CODE REVIEW

**Comment by bbondy** [comment]
Looks good. Great work on all of this!

**Comment by paulcbetts** [comment]
Can you submit this and #10 to Electron itself?

**Comment by bridiver** [comment]
Absolutely @paulcbetts, but this needs a small change first. We temporarily worked around this issue in the browser-laptop code, but right content scripts enabled on renderer start will stay enabled for all pages even if you change them based on url. We will fix this by adding content matching rules like the chrome webview tag, but for now I can pull out the ShouldFork changes related to the work we did for window.opener and create a new PR for Electron.

**Comment by bridiver** [comment]
I could also leave out content scripts entirely for now and come back with another PR when they are ready for general use

**Comment by paulcbetts** [comment]
@bridiver That'd be awesome! What's the difference between content scripts and preload scripts - is it just the node integration aspect?

**Comment by bridiver** [comment]
Yea, the content scripts still have access to ipcRenderer send, sendSync and sendToHost, but the functions are bound to plain v8 objects and they are removed from the global context before the page gets access to the script context. I wanted to keep the functionality without breaking existing node-based preload functionality

**Pull request merged**
